version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: package/docs/conf.py

python:
    install:
    - requirements: package/requirements.txt
    - requirements: package/requirements_dev.txt
