name: AquDeM Frontend Code Quality Check

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        cd frontend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
        cd ../package
        pip install .
    - name: Run tests with pytest
      run: |
        cd frontend
        export PYTHONPATH=.
        pytest
    - name: Lint with pylint
      run: |
        cd frontend
        pylint aqudem_app.py
        pylint --disable=missing-function-docstring tests

