name: AquDeM Code Quality Check

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'package/**'
  push:
    branches: [ main ]
    paths:
      - 'package/**'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        cd package
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
    - name: Run unit tests with pytest
      run: |
        cd package
        export PYTHONPATH=.
        pytest

    - name: Make sure coverage is high enough
      run: |
        cd package
        export PYTHONPATH=.
        coverage run --source=aqudem --branch -m pytest
        coverage report --fail-under=90

    - name: Lint with pylint
      run: |
        cd package
        pylint aqudem
        pylint --disable=protected-access,missing-function-docstring tests

    - name: Type checking with mypy
      run: |
        cd package
        mypy aqudem tests --strict
